#
# _config.yml for Google Cloud Icons
#

exclude: [ "CNAME", "**/*_src*" ]
permalink: /blog/:year/:month/:day/:title/index.:output_ext
production_url: https://gcp-icons.vectorlogo.zone
title: Google Cloud Product Icons
markdown: kramdown
plugins:
  - jekyll-redirect-from
redirect_from:
  json: false
theme: null
links:
  - name: "Download original"
    url: "https://cloud.google.com/icons"
  - name: "Report an issue"
    url: "https://github.com/AwesomeLogos/gcp-icons/issues"