language: objective-c
osx_image: xcode10.2

env:
  - "DESTINATION='OS=12.2,platform=iOS Simulator,name=iPhone 8' ACTION=test"
  - "DESTINATION='platform=macOS' ACTION=test"
  - "DESTINATION='OS=12.2,platform=tvOS Simulator,name=Apple TV' ACTION=test"

script:
  - set -o pipefail && xcodebuild -project Sources/FlagKit.xcodeproj -scheme FlagKit -destination "$DESTINATION" $ACTION | xcpretty
